



package com.message.model;

public enum MessageType
{
    INCOMING_TEXT,
    OUTGOING_TEXT,
    INCOMING_IMAGE,
    OUTGOING_IMAGE,
    INCOMING_CARD_WITH_IMAGE,
    INCOMING_CARD_WITH_TEXT,
    INCOMING_HORIZONTAL_CARD_LIST,
    INCOMING_HORIZONTAL_DOCTOR_CARD_LIST,
    INCOMING_HORIZONTAL_LIST,
    INCOMING_MULTISELECT_LIST,
    INCOMING_CARD_WITH_LIST,
    INCOMING_CART_WITH_LIST,
    INCOMING_CARD_WITH_LIST_VACCINATION,
    INCOMING_TIME_PICKER,
    INCOMING_DATE_PICKER,
    INCOMING_CARD_PAYMENT,
    GENERAL_TEXT,
    INTRODUCTION_TEXT,
    SPINNER,
    INCOMING_VITAL_VALUES,
    INCOMING_CARD_HRA_FAMILY_HISTORY,
    INCOMING_MEMBER_PROFILE_CARD,
    INCOMING_CARD_WITH_LIST_MEDICATION,
    INCOMING_CARD_LIST_WITH_GRAPH,
    INCOMING_CARD_WITH_WELLNESS_LIST,
    OUTGOING_MAP,
    INCOMING_PACKAGE,
    INCOMING_DC_LIST,
    OUTGOING_DC_CARD,
    INCOMING_TEXT_PROGRESS;

    public static final MessageType values[] = values();
}
